[package]
name = "aoc"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
htmd = "0.2.0"
md-5 = "0.11.0-pre.5"
reqwest = { version = "0.12", features = ["blocking", "cookies", "json"] }
scraper = "0.23.1"
